# Dockerfile.dev
FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg

COPY requirements.txt ./
RUN pip install -U --no-cache-dir -r requirements.txt
RUN pip install gunicorn

COPY . .

EXPOSE 5000

CMD ["gunicorn", "server:app", "-w 4", "-b 0.0.0.0:5000", "--log-level=warning"]
